{% set name = "foc" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/foc-{{ version }}.tar.gz
  sha256: cc999b154baf8d777955867e768cc207057455d329430aba850edc553ddb7326

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - foc
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/thyeem/foc
  summary: A collection of python functions for somebody's sanity
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
